export const uz = {
  appbartitle: "Eslatmalar",
  appbarseacrch: "Qidirish...",
  infobar: "Barcha eslatmalar",
  infobarsearch: "Qidirish",
  list: "Roʻyxat",
  grid: "Jadval",
  titlewindow: "Eslatma qo’shish",
  titlewindowedit: "Elsatmani tahrirlash",
  editbtn: "o'zgartirish",
  deledit: "o'chirish",
  closebtn: "Bekor qilish",
  addbtn: "Qo’shish",
  editwindowbtn: "o'zgartirish",
  nonote: "Eslatmalar mavjud emas",
};
export const ru = {
  appbartitle: "Заметки",
  appbarseacrch: "Поиск...",
  infobar: "Все заметки",
  infobarsearch: "Поиск",
  list: "Список",
  grid: "Сетка",
  titlewindow: "Добавить заметку",
  titlewindowedit: "Изменить заметку",
  editbtn: "РЕДАКТИРОВАТЬ",
  deledit: "Удалить",
  closebtn: "Отмена",
  addbtn: "Добавить",
  editwindowbtn: "изменить",
  nonote: "Заметок нет",
};
